---
- hosts: all
  tasks:
  - name: disable all repositories
    command: subscription-manager repos --disable=*
  
  - name: enable necessary repositories
    command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-10-rpms
    
  - name: apply all available patches
    yum:
      name: '*'
      state: latest
  
  - name: restart server
    shell: sleep 2 && shutdown -r now "Patched with Ansible"
    async: 1
    poll: 0
    ignore_errors: true
  
  - name: wait for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
    sudo: false
  
  - name: install OpenStack puppet modules
    yum: name=openstack-puppet-modules state=present

  - name: install OpenStack SELinux modules 
    yum: name=openstack-selinux state=present

  - name: configure puppet
    template: src=templates/puppet.conf.j2 dest=/etc/puppet/puppet.conf mode=0644

  - name: install git
    yum: name=git state=present

  - name: download single repository
    git: repo=https://github.com/msolberg/puppet-singleo dest=/etc/puppet/modules/singleo

  - name: configure hiera
    template: src=templates/hiera.yaml.j2 dest=/etc/puppet/hiera.yaml mode=0644
